### ISSUE TITLE
build failure with ecore2owl.core

### ISSUE THREAD

**Issue by chris-day** [kit-sdq/Ecore2OWL#1]
Hi -

INFO] ------------------------------------------------------------------------
INFO] Reactor Summary for ecore2owl.parent 1.0.0-SNAPSHOT:
INFO]
INFO] ecore2owl.parent ................................... SUCCESS [  0.112 s]
INFO] ecore2owl.bundles .................................. SUCCESS [  0.027 s]
INFO] Ecore2OWL Dependencies Collector ................... SUCCESS [ 25.426 s]
INFO] ecore2owl.dependencies-provider .................... SUCCESS [  2.914 s]
INFO] ecore2owl.OntologyAccess ........................... SUCCESS [  1.314 s]
INFO] ecore2owl.core ..................................... FAILURE [  0.320 s]
INFO] ecore2owl.ui ....................................... SKIPPED
INFO] ecore2owl.features ................................. SKIPPED
INFO] edu.kit.ipd.are.ecore2owl.feature .................. SKIPPED
INFO] ecore2owl.tests .................................... SKIPPED
INFO] ecore2owl.releng ................................... SKIPPED
INFO] Ecore2OWL Update Site .............................. SKIPPED
INFO] ------------------------------------------------------------------------
INFO] BUILD FAILURE
INFO] ------------------------------------------------------------------------
INFO] Total time:  01:39 min
INFO] Finished at: 2020-04-01T08:02:32+01:00
INFO] ------------------------------------------------------------------------
ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:1.5.1:compile (default-compile) on project ecore2
wl.core: Compilation failure: Compilation failure:
ERROR] F:\GitHub\Ecore2OWL\bundles\edu.kit.ipd.are.ecore2owl.core\src\edu\kit\ipd\are\ecore2owl\core\Ecore2OWLTransform
r.java:[260]
ERROR]         .collect(Collectors.toUnmodifiableList());
ERROR]                             ^^^^^^^^^^^^^^^^^^
ERROR] The method toUnmodifiableList() is undefined for the type Collectors
ERROR] F:\GitHub\Ecore2OWL\bundles\edu.kit.ipd.are.ecore2owl.core\src\edu\kit\ipd\are\ecore2owl\core\Ecore2OWLTransform
r.java:[667]
ERROR]         ontologyAccess.addDataPropertyToIndividual(optIndividual.get(), optDataProperty.orElseThrow(),
ERROR]                                                                                         ^^^^^^^^^^^
ERROR] The method orElseThrow(Supplier<? extends X>) in the type Optional<DatatypeProperty> is not applicable for the a
guments ()
ERROR] 2 problems (2 errors)
ERROR] -> [Help 1]
ERROR]
ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
ERROR] Re-run Maven using the -X switch to enable full debug logging.
ERROR]
ERROR] For more information about the errors and possible solutions, please read the following articles:
ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
ERROR]
ERROR] After correcting the problems, you can resume the build with the command
ERROR]   mvn <goals> -rf :ecore2owl.core

**Comment by Gram21** [comment]
Hello @chris-day,
Thank you for your issue. I looked into it and currently cannot reproduce your issue. Both, on travis and on my own machine I cannot trigger the same error you are getting.
Can you provide more information? Which maven and Java version are you using? On what kind of OS?
At least some parts of the error message seem to be an issue with the used Java version. This project needs at least Java 11.

**Comment by chris-day** [comment]
Hi Jan –

 

Thanks for getting back so quickly – I was using Java 8. I’ll retry with Java 11.

 

Cheers

 

Chris 

 

 

c: +44 7930 909 297

p: +44 115 714 0869

s: bigchrisday

 <https://www.linkedin.com/in/chrisdayabinitio/> https://www.linkedin.com/in/chrisdayabinitio/
